apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort
  ports:
    - port: 80           # The port inside the cluster
      targetPort: 80      # The port on the pod that your app is listening on
      nodePort: 30080     # The port on each node (optional, Kubernetes will assign one if not specified)
  selector:
    app: guestbook-ui
